import pyxel
from safari.cards.base import ANIMALS

INVISIBLE_COLOR = pyxel.COLOR_PURPLE

PLAYER_COLORS = [
    pyxel.COLOR_RED,
    pyxel.COLOR_GREEN,
    pyxel.COLOR_YELLOW,
    pyxel.COLOR_NAVY,
]

ASSET_W_SMALL = 16
ASSET_H_SMALL = 16

ANIMAL_TO_ASSETS_MAPPING_SMALL = {
    ANIMALS.SKUNK: (0, 0),
    ANIMALS.PARROT: (16, 0),
    ANIMALS.KANGAROO: (32, 0),
    ANIMALS.MONKEY: (48, 0),
    ANIMALS.CHAMELEON: (0, 16),
    ANIMALS.SEAL: (16, 16),
    ANIMALS.ZEBRA: (32, 16),
    ANIMALS.GAZELLE: (48, 16),
    ANIMALS.SNAKE: (0, 32),
    ANIMALS.CROC: (16, 32),
    ANIMALS.HIPPO: (32, 32),
    ANIMALS.LION: (48, 32),
}

ASSET_H_BIG = 40
ASSET_W_BIG = 32
ANIMAL_TO_ASSETS_MAPPING_BIG = {
    ANIMALS.SKUNK: (0, 48),
    ANIMALS.PARROT: (32, 48),
    ANIMALS.KANGAROO: (64, 48),
    ANIMALS.MONKEY: (96, 48),
    ANIMALS.CHAMELEON: (128, 48),
    ANIMALS.SEAL: (160, 48),
    ANIMALS.ZEBRA: (192, 48),
    ANIMALS.GAZELLE: (224, 48),
    ANIMALS.SNAKE: (0, 88),
    ANIMALS.CROC: (32, 88),
    ANIMALS.HIPPO: (64, 88),
    ANIMALS.LION: (96, 88),
}



